Add license.txt
modelica/fmi-cross-check pull request #118
Opened 2021-07-09 12:23 UTC by chrbertsch

resolves #114

2021-07-09 13:33 UTC, klausschuch requested changes

2021-07-09 13:33 UTC, klausschuch commented on LICENSE.txt
> +The FMUs uploaded to this repository are provided to for testing purposes within the FMI Cross Check only. For this purpose the FMUs may be simulated by in importing tools.
```suggestion
The FMUs uploaded to this repository are provided for testing purposes within the FMI Cross Check only. For this purpose the FMUs may be simulated by importing tools.
```

2021-07-09 13:33 UTC, klausschuch commented on LICENSE.txt
> +More information can be found in the subfolders under https://github.com/modelica/fmi-cross-check/tree/master/fmus and/or the docuementation folder of the FMUs.
```suggestion
More information can be found in the subfolders under https://github.com/modelica/fmi-cross-check/tree/master/fmus and/or the documentation folder of the FMUs.
```

2021-07-09 13:33 UTC, klausschuch commented on LICENSE.txt
> +It is in the responsibility of the providers of the FMUs to comply with license conditions of third parties, e.g., w.r.t open source licenses of software contained in the FMUs or in used in the creat
```suggestion
It is in the responsibility of the providers of the FMUs to comply with license conditions of third parties, e.g., w.r.t. open source licenses of software contained in the FMUs or used in the creation of the FMUs, e.g., by shipping the corresponding license texts within the documentation folder of the FMU.
```

2021-07-26 08:22 UTC, andreas-junghanns approved these changes
@klausschuch : ok now? Can we merge?

2022-02-10 08:25 UTC, merged